name: Notificación de Push
 
on:
  push:
    branches:
      - main
 
jobs:
  notify:
    runs-on: ubuntu-latest
 
    steps:
      - name: DevOps Practica 4 M:2022-1922
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
            -H "Title: 🚀 Nuevo Push al Repositorio" \
            -H "Priority: default" \
            -H "Tags: rocket" \
            -d "Push realizado por ${{ github.actor }} en ${{ github.repository }} — rama: ${{ github.ref_name }} — commit: ${{ github.event.head_commit.message }}"